name: trail_server
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 path: ^1.6.0
 body_parser: ^1.1.1
 sevr: ^1.0.2+3

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
